apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  #these are replica set labels
  labels:
    project: roboshop
    component: mongodb
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  #pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: khajit03/mongodb:v1